sudo: required
services:
- docker
language: go
go:
- '1.9'
script:
- make style
- make lint
- make test
- tools/bin/goveralls -coverprofile=cover.out -service=travis-ci
env:
  global:
    - LINTER_DEADLINE=180s
cache:
  directories:
  - tools/bin
