sudo: required
services:
- docker
language: go
go:
- '1.9'
script:
- make style
- make lint
- make test
- tools/bin/goveralls -coverprofile=cover.out -service=travis-ci
env:
  global:
  - LINTER_DEADLINE=180s
  matrix:
  - PDNS_AUTH_REPO_TAG=xenial-auth-40 PDNS_REC_REPO_TAG=xenial-rec-40
  - PDNS_AUTH_REPO_TAG=xenial-auth-41 PDNS_REC_REPO_TAG=xenial-rec-41
  - PDNS_AUTH_REPO_TAG=xenial-auth-master PDNS_REC_REPO_TAG=xenial-rec-master
matrix:
  allow_failures:
  - env: PDNS_AUTH_REPO_TAG=xenial-auth-41 PDNS_REC_REPO_TAG=xenial-rec-41
  - env: PDNS_AUTH_REPO_TAG=xenial-auth-master PDNS_REC_REPO_TAG=xenial-rec-master
cache:
  directories:
  - tools/bin
